version: "3"
services: 
    reverseproxy:
        build: 
            context: .
        image: maduflavins/reverseproxy
    backend_user:
        build: 
            context: ../../udacity-c3-restapi-user
        image: maduflavins/udacity-restapi-user
    backend_feed:
        build:
            context: ../../udacity-c3-restapi-feed
        image: maduflavins/udacity-restapi-feed
    frontend:
        build:
            context: ../../udacity-c3-frontend
        image: maduflavins/udacity-frontend:local